[package]
name = "adxl314"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Reads ADXL accelerometer data through I2C protocol"
homepage = "https://github.com/purdue-orbital"

[dependencies]
embedded-hal = "1.0.0"
